// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './TimeTrackingCell'
import type { FIND_TIME_TRACKING_BY_ID, FIND_TIME_TRACKING_BY_IDVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './TimeTrackingCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FIND_TIME_TRACKING_BY_ID | 'updating'
> & FIND_TIME_TRACKING_BY_IDVariables

export default function (props: CellInputs): ReturnType<SuccessType>
