declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    dashboard: () => "/"
    newTimeTracking: () => "/time-tracking/new"
    editTimeTracking: () => "/time-tracking/{id:Int}/edit"
    timeTracking: () => "/time-tracking/{id:Int}"
    timeTrackings: () => "/time-tracking"
    invoices: () => "/invoices"
    editInvoice: () => "/invoices/{id:Int}/edit"
    invoice: () => "/invoices/{id:Int}"
    newInvoice: () => "/invoices/new"
    transactions: () => "/transactions"
    editTransaction: () => "/transactions/{id:Int}/edit"
    transaction: () => "/transactions/{id:Int}"
    newTransaction: () => "/transactions/new"
    transactionImport: () => "/transaction-import"
    timeTracking: () => "/time-tracking"
    newTimeTracking: () => "/time-tracking/new"
    clients: () => "/clients"
    editClient: () => "/clients/{id:Int}/edit"
    client: () => "/clients/{id:Int}"
    newClient: () => "/clients/new"
    settings: () => "/settings"
  }
}
