// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './EditClientCell'
import type { FIND_CLIENT_BY_ID, FIND_CLIENT_BY_IDVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditClientCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FIND_CLIENT_BY_ID | 'updating'
> & FIND_CLIENT_BY_IDVariables

export default function (props: CellInputs): ReturnType<SuccessType>
