// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './TransactionsCell'
import type { TRANSACTIONS, TRANSACTIONSVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './TransactionsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof TRANSACTIONS | 'updating'
> & TRANSACTIONSVariables

export default function (props: CellInputs): ReturnType<SuccessType>
