// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './InvoicesCell'
import type { INVOICES, INVOICESVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './InvoicesCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof INVOICES | 'updating'
> & INVOICESVariables

export default function (props: CellInputs): ReturnType<SuccessType>
