// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './InvoiceCell'
import type { FIND_INVOICE_BY_ID, FIND_INVOICE_BY_IDVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './InvoiceCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FIND_INVOICE_BY_ID | 'updating'
> & FIND_INVOICE_BY_IDVariables

export default function (props: CellInputs): ReturnType<SuccessType>
