// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './TimeTrackingsCell'
import type { TIME_TRACKINGS, TIME_TRACKINGSVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './TimeTrackingsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof TIME_TRACKINGS | 'updating'
> & TIME_TRACKINGSVariables

export default function (props: CellInputs): ReturnType<SuccessType>
