// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './ClientsCell'
import type { CLIENTS, CLIENTSVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './ClientsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof CLIENTS | 'updating'
> & CLIENTSVariables

export default function (props: CellInputs): ReturnType<SuccessType>
